2021-06-13 21:28:05,277 [main.py         | 48] INFO: Start to run instance_1
2021-06-13 21:28:05,277 [simulate_api.py | 60] INFO: Start time of the simulator: 2021-06-13 00:00:00, time interval:  600.00
2021-06-13 21:28:05,289 [input_utils.py  | 48] INFO: Get 154 factories
2021-06-13 21:28:06,891 [input_utils.py  | 52] INFO: Get 23562 routes
2021-06-13 21:28:06,933 [input_utils.py  | 57] INFO: Get 5 vehicles
2021-06-13 21:28:06,945 [input_utils.py  | 61] INFO: Get 50 orders
2021-06-13 21:28:06,946 [simulate_api.py | 87] INFO: Initial position of V_1 is e2d5093fbe36431f8986ddb0e1c586be
2021-06-13 21:28:06,948 [simulate_api.py | 87] INFO: Initial position of V_2 is 7fe14b93f0f04ee7a994ef5b2c1fdb72
2021-06-13 21:28:06,949 [simulate_api.py | 87] INFO: Initial position of V_3 is fa366fc87a124d32926daa5bb093129f
2021-06-13 21:28:06,949 [simulate_api.py | 87] INFO: Initial position of V_4 is e47399648fa842b2b8f80094343d8091
2021-06-13 21:28:06,949 [simulate_api.py | 87] INFO: Initial position of V_5 is becb4f85393540b287e7329758b8d832
2021-06-13 21:28:06,949 [simulate_environment.py | 96] INFO: **************************************************
2021-06-13 21:28:06,949 [simulate_environment.py | 100] INFO: cur time: 2021-06-13 00:10:00, pre time: 2021-06-13 00:00:00
2021-06-13 21:28:06,949 [simulate_environment.py | 136] INFO: Start to update the input of 2021-06-13 00:10:00
2021-06-13 21:28:06,950 [simulate_environment.py | 163] INFO: Get 1 unallocated order items, 0 ongoing order items, 0 completed order items
2021-06-13 21:28:07,902 [simulate_environment.py | 240] ERROR: 当前需要决定的requestID: 0003480001
2021-06-13 21:28:07,836 [main_algorithm.py | 32] ERROR: Failed to run algorithm
2021-06-13 21:28:07,837 [main_algorithm.py | 33] ERROR: Error: '0012230002', Traceback (most recent call last):
  File "main_algorithm.py", line 29, in <module>
    scheduling()
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\algorithm\vrppd\main_algorithm.py", line 242, in scheduling
    dvrppd_Solver.constructEngine(time2Go=time_2_go)
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\algorithm\vrppd\DVRPPDSolver.py", line 101, in constructEngine
    if constructor.solve(time2Go=time2Go):
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\algorithm\vrppd\constructor.py", line 42, in solve
    if self._insertionOperator.insert(time2Go=time2Go):
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\algorithm\vrppd\Operator.py", line 519, in insert
    request = self._source_pool.requests.getUnDispatchedPool[requestID]
KeyError: '0012230002'

FAIL

2021-06-13 21:28:07,902 [main.py         | 55] ERROR: Failed to run simulator
2021-06-13 21:28:07,902 [main.py         | 56] ERROR: Error: 未寻获算法输出成功标识SUCCESS, Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/dpdp/simulator/dpdp_competition/main.py", line 51, in <module>
    score = simulate(Configs.factory_info_file, Configs.route_info_file, instance)
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\src\simulator\simulate_api.py", line 94, in simulate
    simulate_env.run()
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\src\simulator\simulate_environment.py", line 107, in run
    used_seconds, dispatch_result = self.dispatch(updated_input_info)
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\src\simulator\simulate_environment.py", line 241, in dispatch
    raise ValueError('未寻获算法输出成功标识SUCCESS')
ValueError: 未寻获算法输出成功标识SUCCESS

