2021-06-13 18:30:33,376 [main.py         | 48] INFO: Start to run instance_1
2021-06-13 18:30:33,376 [simulate_api.py | 60] INFO: Start time of the simulator: 2021-06-13 00:00:00, time interval:  600.00
2021-06-13 18:30:33,389 [input_utils.py  | 48] INFO: Get 154 factories
2021-06-13 18:30:34,999 [input_utils.py  | 52] INFO: Get 23562 routes
2021-06-13 18:30:35,027 [input_utils.py  | 57] INFO: Get 5 vehicles
2021-06-13 18:30:35,038 [input_utils.py  | 61] INFO: Get 50 orders
2021-06-13 18:30:35,038 [simulate_api.py | 87] INFO: Initial position of V_1 is e2d5093fbe36431f8986ddb0e1c586be
2021-06-13 18:30:35,040 [simulate_api.py | 87] INFO: Initial position of V_2 is 7fe14b93f0f04ee7a994ef5b2c1fdb72
2021-06-13 18:30:35,041 [simulate_api.py | 87] INFO: Initial position of V_3 is fa366fc87a124d32926daa5bb093129f
2021-06-13 18:30:35,041 [simulate_api.py | 87] INFO: Initial position of V_4 is e47399648fa842b2b8f80094343d8091
2021-06-13 18:30:35,041 [simulate_api.py | 87] INFO: Initial position of V_5 is becb4f85393540b287e7329758b8d832
2021-06-13 18:30:35,041 [simulate_environment.py | 96] INFO: **************************************************
2021-06-13 18:30:35,041 [simulate_environment.py | 100] INFO: cur time: 2021-06-13 00:10:00, pre time: 2021-06-13 00:00:00
2021-06-13 18:30:35,041 [simulate_environment.py | 136] INFO: Start to update the input of 2021-06-13 00:10:00
2021-06-13 18:30:35,042 [simulate_environment.py | 163] INFO: Get 1 unallocated order items, 0 ongoing order items, 0 completed order items
2021-06-13 18:30:36,143 [simulate_environment.py | 247] INFO: 2021-06-13 00:10:00, Item 0003480001-1: state = 1 < 2, we can not finish the simulation
2021-06-13 18:30:36,143 [simulate_environment.py | 96] INFO: **************************************************
2021-06-13 18:30:36,143 [simulate_environment.py | 100] INFO: cur time: 2021-06-13 00:20:00, pre time: 2021-06-13 00:10:00
2021-06-13 18:30:36,143 [simulate_environment.py | 136] INFO: Start to update the input of 2021-06-13 00:20:00
2021-06-13 18:30:36,148 [simulate_environment.py | 163] INFO: Get 3 unallocated order items, 0 ongoing order items, 0 completed order items
2021-06-13 18:30:37,252 [simulate_environment.py | 240] ERROR: ['0003480001', '0012230002', '0013570003']
vehicleID:  V_3 requestID:  0 demandType:   depot customerID:  fa366fc87a124d32926daa5bb093129f      arrive_time: 2021-06-13 00:30:00 leave_time: 2021-06-13 00:30:00
vehicleID:  V_3 requestID:  0003480001 demandType:   pickup customerID:  2445d4bd004c457d95957d6ecf77f759      arrive_time: 2021-06-13 00:47:24 leave_time: 2021-06-13 01:23:24 travel_time:  17.4 dis:  8.7
vehicleID:  V_3 requestID:  0012230002 demandType:   pickup customerID:  2445d4bd004c457d95957d6ecf77f759      arrive_time: 2021-06-13 00:47:24 leave_time: 2021-06-13 01:23:24 travel_time:  0.0 dis:  0
vehicleID:  V_3 requestID:  0013570003 demandType:   pickup customerID:  ffd0ed8719f54294a452ed3e3b6a986c      arrive_time: 2021-06-13 01:39:12 leave_time: 2021-06-13 02:10:12 travel_time:  15.8 dis:  7.9
vehicleID:  V_3 requestID:  0013570003 demandType:   delivery customerID:  9f1a09c368584eba9e7f10a53d55caae      arrive_time: 2021-06-13 02:15:12 leave_time: 2021-06-13 02:50:12 travel_time:  5.0 dis:  0.1
vehicleID:  V_3 requestID:  0012230002 demandType:   delivery customerID:  9f1a09c368584eba9e7f10a53d55caae      arrive_time: 2021-06-13 02:15:12 leave_time: 2021-06-13 02:50:12 travel_time:  0.0 dis:  0
vehicleID:  V_3 requestID:  0003480001 demandType:   delivery customerID:  b6dd694ae05541dba369a2a759d2c2b9      arrive_time: 2021-06-13 02:51:36 leave_time: 2021-06-13 03:23:36 travel_time:  1.4 dis:  0.7
score is: 17.400000000000002
customerID is: 2445d4bd004c457d95957d6ecf77f759 port ID is: 0 [vehicleID is: V_3 requestID is  0003480001    arrive_time is: 2021-06-13 00:47:24 leave_time is: 2021-06-13 01:23:24 ] 
customerID is: b6dd694ae05541dba369a2a759d2c2b9 port ID is: 0 [vehicleID is: V_3 requestID is  0003480001    arrive_time is: 2021-06-13 02:51:36 leave_time is: 2021-06-13 03:23:36 ] 
customerID is: 9f1a09c368584eba9e7f10a53d55caae port ID is: 0 [vehicleID is: V_3 requestID is  0013570003    arrive_time is: 2021-06-13 02:15:12 leave_time is: 2021-06-13 02:50:12 ] 
customerID is: ffd0ed8719f54294a452ed3e3b6a986c port ID is: 0 [vehicleID is: V_3 requestID is  0013570003    arrive_time is: 2021-06-13 01:39:12 leave_time is: 2021-06-13 02:10:12 ] 
2021-06-13 18:30:37,185 [main_algorithm.py | 32] ERROR: Failed to run algorithm
2021-06-13 18:30:37,186 [main_algorithm.py | 33] ERROR: Error: 'NoneType' object has no attribute 'requestID', Traceback (most recent call last):
  File "main_algorithm.py", line 29, in <module>
    scheduling()
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\algorithm\vrppd\main_algorithm.py", line 242, in scheduling
    dvrppd_Solver.constructEngine(time2Go=time_2_go)
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\algorithm\vrppd\DVRPPDSolver.py", line 106, in constructEngine
    checker(self._vehiclesPool)
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\algorithm\vrppd\utlis.py", line 203, in checker
    if index > 0 and node.requestID != node.brotherNode.requestID:
AttributeError: 'NoneType' object has no attribute 'requestID'

FAIL

2021-06-13 18:30:37,256 [main.py         | 55] ERROR: Failed to run simulator
2021-06-13 18:30:37,256 [main.py         | 56] ERROR: Error: 未寻获算法输出成功标识SUCCESS, Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/dpdp/simulator/dpdp_competition/main.py", line 51, in <module>
    score = simulate(Configs.factory_info_file, Configs.route_info_file, instance)
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\src\simulator\simulate_api.py", line 94, in simulate
    simulate_env.run()
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\src\simulator\simulate_environment.py", line 107, in run
    used_seconds, dispatch_result = self.dispatch(updated_input_info)
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\src\simulator\simulate_environment.py", line 241, in dispatch
    raise ValueError('未寻获算法输出成功标识SUCCESS')
ValueError: 未寻获算法输出成功标识SUCCESS

