2021-06-13 18:42:42,176 [main.py         | 48] INFO: Start to run instance_1
2021-06-13 18:42:42,176 [simulate_api.py | 60] INFO: Start time of the simulator: 2021-06-13 00:00:00, time interval:  600.00
2021-06-13 18:42:42,188 [input_utils.py  | 48] INFO: Get 154 factories
2021-06-13 18:42:43,745 [input_utils.py  | 52] INFO: Get 23562 routes
2021-06-13 18:42:43,775 [input_utils.py  | 57] INFO: Get 5 vehicles
2021-06-13 18:42:43,785 [input_utils.py  | 61] INFO: Get 50 orders
2021-06-13 18:42:43,785 [simulate_api.py | 87] INFO: Initial position of V_1 is e2d5093fbe36431f8986ddb0e1c586be
2021-06-13 18:42:43,787 [simulate_api.py | 87] INFO: Initial position of V_2 is 7fe14b93f0f04ee7a994ef5b2c1fdb72
2021-06-13 18:42:43,788 [simulate_api.py | 87] INFO: Initial position of V_3 is fa366fc87a124d32926daa5bb093129f
2021-06-13 18:42:43,788 [simulate_api.py | 87] INFO: Initial position of V_4 is e47399648fa842b2b8f80094343d8091
2021-06-13 18:42:43,788 [simulate_api.py | 87] INFO: Initial position of V_5 is becb4f85393540b287e7329758b8d832
2021-06-13 18:42:43,788 [simulate_environment.py | 96] INFO: **************************************************
2021-06-13 18:42:43,788 [simulate_environment.py | 100] INFO: cur time: 2021-06-13 00:10:00, pre time: 2021-06-13 00:00:00
2021-06-13 18:42:43,788 [simulate_environment.py | 136] INFO: Start to update the input of 2021-06-13 00:10:00
2021-06-13 18:42:43,789 [simulate_environment.py | 163] INFO: Get 1 unallocated order items, 0 ongoing order items, 0 completed order items
2021-06-13 18:42:44,909 [simulate_environment.py | 247] INFO: 2021-06-13 00:10:00, Item 0003480001-1: state = 1 < 2, we can not finish the simulation
2021-06-13 18:42:44,909 [simulate_environment.py | 96] INFO: **************************************************
2021-06-13 18:42:44,909 [simulate_environment.py | 100] INFO: cur time: 2021-06-13 00:20:00, pre time: 2021-06-13 00:10:00
2021-06-13 18:42:44,909 [simulate_environment.py | 136] INFO: Start to update the input of 2021-06-13 00:20:00
2021-06-13 18:42:44,913 [simulate_environment.py | 163] INFO: Get 3 unallocated order items, 0 ongoing order items, 0 completed order items
2021-06-13 18:42:46,378 [simulate_environment.py | 247] INFO: 2021-06-13 00:20:00, Item 0003480001-1: state = 1 < 2, we can not finish the simulation
2021-06-13 18:42:46,378 [simulate_environment.py | 96] INFO: **************************************************
2021-06-13 18:42:46,379 [simulate_environment.py | 100] INFO: cur time: 2021-06-13 00:30:00, pre time: 2021-06-13 00:20:00
2021-06-13 18:42:46,379 [simulate_environment.py | 136] INFO: Start to update the input of 2021-06-13 00:30:00
2021-06-13 18:42:46,383 [simulate_environment.py | 163] INFO: Get 3 unallocated order items, 0 ongoing order items, 0 completed order items
2021-06-13 18:42:47,369 [simulate_environment.py | 240] ERROR: ['0013570003', '0012230002', '0003480001']
vehicleID:  V_2 requestID:  0 demandType:   depot customerID:  7fe14b93f0f04ee7a994ef5b2c1fdb72      arrive_time: 2021-06-13 00:40:00 leave_time: 2021-06-13 00:40:00
vehicleID:  V_2 requestID:  0003480001 demandType:   pickup customerID:  2445d4bd004c457d95957d6ecf77f759  brother customerID b6dd694ae05541dba369a2a759d2c2b9      arrive_time: 2021-06-13 00:56:48 leave_time: 2021-06-13 01:32:48 travel_time:  16.8 dis:  8.4
2021-06-13 18:42:47,306 [main_algorithm.py | 32] ERROR: Failed to run algorithm
2021-06-13 18:42:47,307 [main_algorithm.py | 33] ERROR: Error: 'NoneType' object has no attribute 'customerID', Traceback (most recent call last):
  File "main_algorithm.py", line 29, in <module>
    scheduling()
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\algorithm\vrppd\main_algorithm.py", line 242, in scheduling
    dvrppd_Solver.constructEngine(time2Go=time_2_go)
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\algorithm\vrppd\DVRPPDSolver.py", line 105, in constructEngine
    self._print_solution()
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\algorithm\vrppd\DVRPPDSolver.py", line 152, in _print_solution
    " brother customerID", node.brotherNode.customerID,
AttributeError: 'NoneType' object has no attribute 'customerID'

FAIL

2021-06-13 18:42:47,369 [main.py         | 55] ERROR: Failed to run simulator
2021-06-13 18:42:47,370 [main.py         | 56] ERROR: Error: 未寻获算法输出成功标识SUCCESS, Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/dpdp/simulator/dpdp_competition/main.py", line 51, in <module>
    score = simulate(Configs.factory_info_file, Configs.route_info_file, instance)
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\src\simulator\simulate_api.py", line 94, in simulate
    simulate_env.run()
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\src\simulator\simulate_environment.py", line 107, in run
    used_seconds, dispatch_result = self.dispatch(updated_input_info)
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\src\simulator\simulate_environment.py", line 241, in dispatch
    raise ValueError('未寻获算法输出成功标识SUCCESS')
ValueError: 未寻获算法输出成功标识SUCCESS

